trigger:
- main

name: '$(Date:%y).$(DayOfYear).$(Rev:r)'

pool:
  vmImage: windows-2022

steps:

- task: gitversion/setup@0
  displayName: Install GitVersion
  inputs:
    versionSpec: 5.8.x

- task: gitversion/execute@0
  displayName: Determine Version
  inputs:
    useConfigFile: true
    configFilePath: GitVersion.yml

- task: DotNetCoreCLI@2
  displayName: Restore packages
  inputs:
    command: restore
    projects: src/tom.sln

- task: DotNetCoreCLI@2
  displayName: Build solution
  inputs:
    command: build
    projects: src/tom.sln
    arguments: '--no-restore --configuration Debug --property:PackageOutputPath=$(Build.ArtifactStagingDirectory)'

- task: DotNetCoreCLI@2
  displayName: Publish self-contained (linux-x64)
  inputs:
    command: publish
    publishWebProjects: false
    projects: src/tom.exe/tom.exe.csproj
    arguments: '--no-restore --configuration Debug --runtime linux-x64 --output $(Build.ArtifactStagingDirectory)/tom.exe/linux-x64/'
    zipAfterPublish: false
    modifyOutputPath: false

- task: DotNetCoreCLI@2
  displayName: Publish self-contained (win-x64)
  inputs:
    command: publish
    publishWebProjects: false
    projects: src/tom.exe/tom.exe.csproj
    arguments: '--no-restore --configuration Debug --runtime win-x64 --output $(Build.ArtifactStagingDirectory)/tom.exe/win-x64/'
    zipAfterPublish: false
    modifyOutputPath: false

- powershell: |
    Rename-Item -Path '$(Build.ArtifactStagingDirectory)/tom.exe/linux-x64/Unlimitedinf.Tom.Exe' -NewName 'tom' -Force -Verbose;
    Rename-Item -Path '$(Build.ArtifactStagingDirectory)/tom.exe/win-x64/Unlimitedinf.Tom.Exe.exe' -NewName 'tom.exe' -Force -Verbose;
  displayName: Rename self-contained output files

- task: DeleteFiles@1
  displayName: Delete non-exes from publish
  inputs:
    sourceFolder: $(Build.ArtifactStagingDirectory)/tom.exe
    contents: |
      **/*.pdb
      **/*.xml

- task: PublishBuildArtifacts@1
  displayName: Publish build artifacts
  inputs:
    pathToPublish: $(Build.ArtifactStagingDirectory)
    artifactName: drop
    publishLocation: Container
