trigger:
- master

pool:
  vmImage: windows-2022

name: '$(Date:%y).$(DayOfYear).$(Rev:r)'

steps:

- task: gitversion/setup@0
  displayName: Install GitVersion
  inputs:
    versionSpec: 5.8.x

- task: gitversion/execute@0
  displayName: Determine Version
  inputs:
    useConfigFile: true
    configFilePath: GitVersion.yml

- task: DotNetCoreCLI@2
  inputs:
    command: restore
    projects: src/tom.sln

- task: DotNetCoreCLI@2
  inputs:
    command: custom
    custom: pack
    arguments: src/tom/tom.csproj --configuration Debug --no-restore --output $(Build.ArtifactStagingDirectory) 

- task: PublishBuildArtifacts@1
  displayName: Publish build artifacts
  inputs:
    pathToPublish: $(Build.ArtifactStagingDirectory)
    artifactName: drop
    publishLocation: Container

- task: DotNetCoreCLI@2
  inputs:
    command: push
    nugetFeedType: external
    externalEndpoint: f3d8b226-1860-4e09-81b1-d0a4d3ffcb6f
    packagesToPush: $(Build.ArtifactStagingDirectory)/*.nupkg
