trigger:
- master

pool:
  vmImage: windows-2022

name: '$(Date:%y).$(DayOfYear).$(Rev:r)'

steps:

- task: gitversion/setup@0
  displayName: Install GitVersion
  inputs:
    versionSpec: 5.8.x

- task: gitversion/execute@0
  displayName: Determine Version
  inputs:
    useConfigFile: true
    configFilePath: GitVersion.yml

- task: DotNetCoreCLI@2
  displayName: Restore packages
  inputs:
    command: restore
    projects: src/tom.sln

- task: DotNetCoreCLI@2
  displayName: Build and pack to staging directory
  inputs:
    command: custom
    custom: pack
    arguments: src/tom/tom.csproj --configuration Debug --no-restore --output $(Build.ArtifactStagingDirectory) --no-self-contained

- task: PublishBuildArtifacts@1
  displayName: Publish build artifacts
  inputs:
    pathToPublish: $(Build.ArtifactStagingDirectory)
    artifactName: drop
    publishLocation: Container

- task: NuGetCommand@2
  displayName: NuGet push
  inputs:
    command: push
    nuGetFeedType: external
    publishFeedCredentials: 'NuGet-unlimitedinf'