# Tom Postler, 2017-09-05
# Update the LocalAssemblyInfo.g.cs for a project

param(
    [Parameter(Mandatory=$true)][string]$ProjectDir,
    [Parameter(Mandatory=$true)][string]$AssemblyName
)

# Set CWD to script location
Push-Location $PSScriptRoot
[Environment]::CurrentDirectory = $PWD

$Major, $Minor, $Patch, $Prerelease, $Build = .\Get-VersionInfo.ps1 -AssemblyName $AssemblyName
if ([string]::IsNullOrEmpty($Prerelease)) {
	$Prerelease = "0";
}

# If there's nothing in the Properties dir, then it won't be there...
$dirname = "$ProjectDir\Properties";
if (!(Test-Path $dirname)) {
    New-Item -ItemType Directory $dirname | Out-Null
}

# The file contents
$filename = "$ProjectDir\Properties\LocalAssemblyInfo.g.cs";
@"
//
// This code was generated by a tool. Any changes made manually will be lost the next time this code is regenerated.
//

using System.Reflection;

[assembly: AssemblyTitle("{4}")]
[assembly: AssemblyProduct("{4}")]

[assembly: AssemblyVersion("{0}.{1}.0.0")]
[assembly: AssemblyFileVersion("{0}.{1}.{2}.{3}")]
"@ -f $Major, $Minor, $Patch, $Prerelease, $AssemblyName > $filename;

Write-Host $("Generated local assembly info: {0}.{1}.{2}.{3} in {4}" -f $Major, $Minor, $Patch, $Prerelease, $filename);

# Restore CWD
Pop-Location
[Environment]::CurrentDirectory = $PWD
